lib/ship.rb
This makes the Class ship format work to create instance variables of Ship.
=> Make the class Ship format

lib/ship.rb, spec/ship_spec.rb
Makes the attr_reader tests pass.
=> Make the attributes/respective tests and start the sunk? method

spec/ship_spec.rb
sunk? method seems to be in working order.
=> Make the sunk method work/pass its test

lib/ship.rb, spec/ship_spec.rb
Hit method buggy (perhaps?), pushing so you have the code
=> Add hit method; create/pass hit method test

lib/cell.rb, spec/cell_spec.rb
This will make the test for the place_ship method. I wrote it so it should only place the ship in that spot if that spot is nil as to not erase another ships spot.
=> make the place_ship method pass its test

lib/cell.rb, spec/cell_spec.rb
This will make the fire_upon method work
=> Fire upon method

lib/cell.rb, spec/cell_spec.rb
This should make our fired_upon? method "bulletproof"
=> Fired upon method

lib/cell.rb, spec/cell_spec.rb
Worked on method and tests together - next time, will commit separate branches for each
=> Add render method; Create/pass render tests

lib/board.rb, spec/board_spec.rb
Initialized Board class and created/passed 'it exists' test
=> Add Board class; Create/pass initial Board tests

lib/board.rb, spec/board_spec.rb
This will finalize out tests, and make the cells method pass.
=> Make the cells method tests; method passes the tests

lib/board.rb, lib/ship.rb
Refactored the cells method into the initialize as attribute to make it accessible to every instance of board.
=> Board class

lib/ship.rb
Refactors our hit method to work the way we want
=> Refactor hit method to return what we want

lib/board.rb
Thought it would be easier to have the symbol names match up with the coordinates in the @cells hash. Let me know what you think!
=> Refactor the symbol names of the @cells hash

lib/board.rb, spec/board_spec.rb
Add valid_coordinate? method; Refactor hash key symbols to strings
=> Add valid_coordinate? method

spec/board_spec.rb
=> Overlap test

lib/board.rb, spec/board_spec.rb
I did a lot of messing around in another local branch. This was the simplest way I could make sense of it. The `split` method was key to dissecting the numbers and letters into their own arrays to mess with.  I did the same thing for letters and numbers with slight variations of methods (`.to_i` for number strings to integers, and `.ord` to assign integers to letters) to figure out whether they are consecutive or not.
=> Finalized valid placement

lib/board.rb, spec/board_spec.rb
=> Add Board render method

battleship_runner.rb, lib/board.rb, lib/computer.rb, lib/game.rb, lib/player.rb, lib/turn.rb, spec/computer_spec.rb, spec/player_spec.rb
This gives us a good foundation to mess with and finish iteration 3 tomorrow.  There is a lot so I will go over it all with you tomorrow. Essentially the Game class will use all our helper methods from every other classes to tell out runner what to do.
=> Game class

lib/computer.rb
remove attr_accessor and place attr_reader
=> finalize the refactoring

lib/computer.rb
Reverts anthonytallent/battleship#38
=> Revert "finalize the refactoring"
